Enable argument passing from Makefile to test script. Primary use is to collect testcase coverage data via Devel::Cover. Sample usage:     make COVERAGE=1 ARGS=--keep-going test
Signed-off-by:  Henry Cox <henry.cox@mediatek.com>

diff --git a/tests/bin/test_run b/tests/bin/test_run
--- a/tests/bin/test_run
+++ b/tests/bin/test_run
@@ -13,10 +13,39 @@ trap 'echo ; exit 1' SIGINT
 [[ -z "$TOPDIR" ]] && TOPDIR=$(readlink -f $(dirname $0)/..) && test -d "$TOPDIR"
 
 source "$TOPDIR/bin/common"
+#echo $@
 
 EXCERPTLEN=10
 TESTNAME="$1"
 shift
+SCRIPT=$1
+shift
+
+OPTS=''
+while [ $# -gt 0 ] ; do
+
+    OPT=$1
+    shift
+    case $OPT in
+
+	--script-args )
+	    OPTS="$OPTS $1"
+	    shift
+	    ;;
+
+	--coverage )
+	    COVER_DB=$1
+	    shift
+	    OPTS="$OPTS $OPT $COVER_DB"
+	    ;;
+
+	* )
+	    echo "Error: test_run: unexpected option '$OPT'"
+	    exit 1
+	    ;;
+
+    esac
+done
 
 TIME=$(type -P time 2>/dev/null)
 if [ ! -z "$TIME" ] ; then
@@ -37,11 +66,11 @@ linux*)
     ;;
 esac
 
-t_detail "COMMAND" "\"$*\"" >>"$LOGFILE"
+t_detail "COMMAND" "\"$SCRIPT $OPTS*\"" >>"$LOGFILE"
 t_detail "OUTPUT" "" >>"$LOGFILE"
 
 # Run command
-$TIME bash -c "$*" 2>&1 | t_indent >>"$LOGFILE"
+$TIME bash -c "$SCRIPT $OPTS" 2>&1 | t_indent >>"$LOGFILE"
 RC=$?
 
 # Evaluate output of time command
