test: Improve test framework
Various improvements to lcov's self-test framework:
 - Add test case for lcov --diff
 - Add new verbosity level
 - Enable normalization of coverage data files from stdin
 - Fix lcov_add_concatenated4 test name

Signed-off-by: Peter Oberparleiter <oberpar@linux.vnet.ibm.com>

diff --git a/test/lcov_add_files/add_test b/test/lcov_add_files/add_test
--- a/test/lcov_add_files/add_test
+++ b/test/lcov_add_files/add_test
@@ -41,6 +41,6 @@ fi
 
 echo "Comparing with reference..."
 if ! diff -u "$REFFILE" "$SORTFILE" ; then
-	echo "Error: Result of addition differs from reference file" >&2
+	echo "Error: Result of combination differs from reference file" >&2
 	exit 1
 fi
